// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 CodeNav Ltd and contributors

import { request as httpsRequest } from "node:https";
import { rootCertificates } from "node:tls";

export async function enrollAgent(options: {
  panelUrl: string;
  token: string;
  publicKeyPem: string;
  fetchImpl?: typeof fetch;
  tlsCa?: string;
}): Promise<{ agentId: string; panelPublicKey: string; wsUrl: string }> {
  const origin = options.panelUrl.replace(/\/$/, "");
  let response: Response;
  try {
    response = await (options.fetchImpl ?? (options.tlsCa ? trustedFetch(options.tlsCa) : fetch))(
      `${origin}/_agent/enroll`,
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ token: options.token, publicKey: options.publicKeyPem }),
      },
    );
  } catch (error) {
    throw new Error(
      `Could not reach the panel at ${origin}. ${describeConnectFailure(error)} Use the current panel address, including its http:// or https:// scheme and port. For self-signed HTTPS, use the enrollment command generated by Certificates-enabled panels.`,
      { cause: error },
    );
  }
  if (!response.ok) {
    throw new Error(`The panel at ${origin} refused enrollment (HTTP ${response.status}).`);
  }
  const body = (await response.json()) as {
    agentId?: string;
    panelPublicKey?: string;
    wsUrl?: string;
  };
  if (!body.agentId || !body.panelPublicKey) throw new Error("Enrollment failed.");
  return { agentId: body.agentId, panelPublicKey: body.panelPublicKey, wsUrl: body.wsUrl ?? "" };
}

/** Scope trust to the supplied panel certificate; never disable TLS verification. */
function trustedFetch(ca: string): typeof fetch {
  return async (input, init) => {
    const url = new URL(String(input));
    if (url.protocol !== "https:")
      throw new Error("A panel trust certificate requires an HTTPS address.");
    return new Promise<Response>((resolve, reject) => {
      const req = httpsRequest(
        url,
        {
          method: init?.method ?? "GET",
          ca: [...rootCertificates, ca],
          timeout: 30_000,
          headers: { "content-type": "application/json" },
        },
        (res) => {
          const chunks: Buffer[] = [];
          let size = 0;
          res.on("data", (chunk: Buffer) => {
            size += chunk.length;
            if (size > 64 * 1024) {
              res.destroy(new Error("The enrollment response was too large."));
              return;
            }
            chunks.push(chunk);
          });
          res.on("error", reject);
          res.on("end", () =>
            resolve(new Response(Buffer.concat(chunks), { status: res.statusCode ?? 500 })),
          );
        },
      );
      req.on("timeout", () => req.destroy(new Error("The HTTPS enrollment request timed out.")));
      req.on("error", reject);
      req.end(typeof init?.body === "string" ? init.body : undefined);
    });
  };
}

function describeConnectFailure(error: unknown): string {
  const code = causeCode(error);
  if (
    code === "UND_ERR_CONNECT_TIMEOUT" ||
    code === "ETIMEDOUT" ||
    code === "UND_ERR_HEADERS_TIMEOUT"
  ) {
    return "The connection timed out.";
  }
  if (code === "ECONNREFUSED") return "Nothing accepted the connection.";
  if (code === "ENOTFOUND" || code === "EAI_AGAIN") return "The address did not resolve.";
  if (code === "ECONNRESET") return "The connection was closed.";
  const cause = error instanceof Error ? error.cause : undefined;
  if (cause instanceof Error && cause.message && cause.message !== "fetch failed")
    return cause.message;
  return "The connection failed.";
}

function causeCode(error: unknown): string {
  const cause = error instanceof Error ? error.cause : undefined;
  if (cause && typeof cause === "object" && "code" in cause && typeof cause.code === "string") {
    return cause.code;
  }
  return "";
}
